name: Run tests
"on":
    push:
        branches:
            - main
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./app
        steps:
            - uses: actions/checkout@v2
            - run: npm ci
            - run: npm run test-ci